categories = ["DayTime Events", "Bites", "Clothing", "Art", "Night Life", "Alternative Ideas"]

categories.each do |category|
  Category.create(name: category)
end

users = [{first_name: "Kwamena", last_name: "Amissah", username: "kwamamissah", email: "kwamamissah@yahoo.com", password: "kwam", img_url: "drake.jpg"}, {first_name: "William", last_name: "George", username: "wgeorge1990", email: "williameverettgeorge@gmail.com", password: "will", img_url: "arnie.jpg"}, {first_name: "Paris", last_name: "Tuzun", username: "paristuzun", email: "paristuzun@gmail.com", password: "paris", img_url: "ellen.jpg"} ]




users.each do |user|
  User.create(user)
end

stone_mountain_trail = CityGem.create(name: "Stone Mountain Trails", description: "Stone Mountain Park features 15 miles of hiking and walking trails, including the 1 mile trail to the top of the mountain", address: "1000 Robert E Lee Blvd, Stone Mountain, GA 30083", category_id: 1, img_url: "https://www.atlantatrails.com/wp-content/uploads/2017/05/stone-mountain-georgia-hiking-1024x683@2x.jpg" )
victory_creek_fall = CityGem.create(name: "Vickery Creek Falls Roswell Mill", description: "Scenic place featuring a historic mill, covered bridge & man-made waterfall, plus hiking trails.", address: "95 Mill St, Roswell, GA 30075", category_id: 1, img_url: "https://i.ytimg.com/vi/3ycLB4oVNA4/maxresdefault.jpg" )
roswell_mill_waterfalls= CityGem.create(name: "Roswell Mill Waterfall", description: "Man-Made Waterfall", address: "1 Mill St, Roswell, GA 30075", category_id: 1, img_url: "https://www.atlantatrails.com/wp-content/uploads/2017/01/roswell-mill-vickery-creek-01-763x509.jpg" )
charleston_bike_trail = CityGem.create(name: "Charleston Park Mountain Bike Trail ", description: "This public space, one of many on Lake Lanier, has boat ramps, docks & picnic tables with grills.", address: "5850 Charleston Park Rd, Cumming, GA 30041", category_id: 1, img_url: "https://lh5.googleusercontent.com/proxy/OBLFFuAPtScGm14CB38wGDFiN3_pxfRGa10eGPg0UBprq1OkFVEVPBa-I7g9xI-s5baHBfUJmOJ2C64N6-qZwcsgSeIrTSkeAeBk1BfT0DR-edPtKZMdZ5MBQMqpXqw8UG-g9z_ikelkLFl055wWOZ53q5p7-q0=w227-h127-k-no" )
jones_bridge_park = CityGem.create(name: "Jones Bridge Park Trail", description: "Tranquil setting featuring a playground, sand volleyball court & river with swim & fishing areas.", address: "4901 E Jones Bridge Rd, Peachtree Corners, GA 30092", category_id: 1, img_url: "https://lh6.googleusercontent.com/proxy/Md8EHKNYqGjfhZE1eHb_zAP-G_eC6f2A9WNWoXwzeh83s3Ps7lKKkpMckAAQnJ5OY4O26WAOvIEgDiBvNXKmiFSnQDmBkPL9HqtXjPAZMwVP2QGnAd4WxP6Q0d-GT-pHD4I7qo9SeGMJwljDIS5jD9Pmsr4=w227-h114-k-no" )
lullwater_preserve = CityGem.create(name: "Lullwater Preserve", description: "Run or walk the scenic trails at Lullwater Park, following the banks of a serene lake and crossing a span bridge to explore the ruins of a 1920s powerhouse.", address: "1463 Clifton Rd, Decatur, GA 30033", category_id: 1, img_url: "https://lh6.googleusercontent.com/proxy/XMNAIGrnXfn_1_oSP-g1MmOkt6GVCU7V8J3zyqC-lzGBwZeCM8GvQIHp_cF50wRb-SmMoGlB-Rxvn-ySlnXFD31bVP4Vi_YvyPLW1B72pP0Odn6u8hm1A22ro4z7hHbC7hvqt-mAcUdlSjeE8LNpHnAY687SGx8=w160-h160-k-no" )
sweetwater_creek_park = CityGem.create(name: "Sweetwater Creek State Park", description: "Hike Sweetwater Creek State Park’s fantastic running and hiking trails near Atlanta, exploring a rushing, whitewater-filled creek, Civil War mill ruins and a beautiful, rolling forest.", address: "1750 Mt Vernon Rd, Lithia Springs, GA 30122", category_id: 1, img_url: "https://lh6.googleusercontent.com/proxy/_dmtDidsr0eOTp4k52h7hURmh2jGycb_W-0V-v_qNOx_8432V6XpVd_IGUQJ3HsONdK7SxpxkBvAfm564c9Ph0VtANCDkjSkXlItlOmQzFHTkKv0jM_IvjVRucO9vmiR0GtcUEzcTUmOfwh90uS6Tce3cvFHq3Y=w227-h151-k-no" )
arabia_mountain= CityGem.create(name: "Arabia Mountain National Heritage Area", description: "The Arabia Mountain National Heritage Area is a wonderland of stunningly diverse landscapes just east of Atlanta. The park’s rolling terrain boasts over thirty miles of prime hiking trails that explore lofty mountaintops, serene lakes, open grasslands, and stream-filled forests.", address: "3350 Klondike Rd, Lithonia, GA 30038" , category_id: 1, img_url: "https://lh5.googleusercontent.com/p/AF1QipPD0YwQZePttsAYIZX-6akrXkNLeXqLqJBOGEvq=w284-h160-k-no" )
morgan_falls = CityGem.create(name: "Morgan Falls Overlook Park", description: "Family-oriented park featuring expansive playgrounds, walking trails, picnic areas & river views.", address: "200 Morgan Falls Rd, Sandy Springs, GA 30350", category_id: 1, img_url: "https://media-cdn.tripadvisor.com/media/photo-s/0d/c1/01/02/morgan-falls-overlook.jpg" )
wild_animal_safari = CityGem.create(name: "Wild Animal Safari", description: "Drive-thru safari park with 65 types of exotic animals, plus bus tours & walking paths.", address: "1300 Oak Grove Rd, Pine Mountain, GA 31822", category_id: 1, img_url: "https://animalsafari.com/Georgia/wp-content/uploads/2017/02/cropped-was512x512icon-1-870x480.png" )
the_beltline= CityGem.create(name: "The Beltline ", description: "The BeltLine is a former railway corridor around the core of Atlanta, Georgia, under development in stages as a multi-use trail. Some portions are already complete, while others are still in a rough state but hikeable.", address: "675 Ponce De Leon Ave NE, Atlanta, GA 30308
", category_id: 1, img_url: "https://network.thehighline.org/content/uploads/sites/3/2017/01/EST_42316_169-web-feat-test.jpg" )
octane = CityGem.create(name: "Octane ", description: "Funky haunt featuring coffee beverages, craft cocktails, beers, & wines in a chill atmosphere.", address: "1280, Peachtree St NE, Atlanta, GA 30309", category_id: 1, img_url: "https://images1.newscred.com/Zz0yZWUzNzg0ZWViYzdhNmViMWE5Nzg0YThiYTYwYzE0NA==" )
dancing_goats= CityGem.create(name: "Dancing Goats", description: "Large, industrial space for coffee from signature roaster Batdorf & Bronson plus cappuccino & tea.", address: "419 W Ponce de Leon Ave, Decatur, GA 30030", category_id: 1, img_url: "https://i.pinimg.com/originals/e8/e8/69/e8e8699bc690284c38661eee5ce680cc.webp" )
revelator_coffee= CityGem.create(name: "Revelator Coffee Grant Park", description: "Industrial-chic cafe serves a variety of espresso beverages, light bites & cocktails at night.", address: "437 Memorial Dr SE A5, Atlanta, GA 30312", category_id: 1, img_url: "https://cdn.shopify.com/s/files/1/1907/0145/files/IMG_5498_1.JPG?6408451254335257792")
inman_perk = CityGem.create(name: "Inman Perk Coffee", description: "Independent neighborhood coffee shop serves up an extensive drink menu, desserts & local art.", address: "240 North Highland Avenue Northeast h, Atlanta, GA 30307", category_id: 1, img_url: "https://media-cdn.tripadvisor.com/media/photo-s/08/23/2f/74/inman-perk.jpg" )
san_fran_coffee = CityGem.create(name: "San Francisco Coffee Roasting Co.", description: "This atmospheric neighborhood hangout roasts its own coffee and bakes most of its own pastries.", address: "1192 North Highland Avenue Northeast, Atlanta, GA 30306", category_id: 1, img_url: "https://s3-media1.fl.yelpcdn.com/bphoto/FRjR738Z_67LqAT4fctgZQ/ls.jpg" )
bqe = CityGem.create(name: "BQE", description: "Trendy pick with warm ambiance dishing up Southern comfort food & New York-themed cocktails.", address: "262 Edgewood Ave NE, Atlanta, GA 30303", category_id: 2, img_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRt0BSaRnL_-n617737I2mN-OFAhcFALWNleXRUoa5GGyiKnxIt" )
negril = CityGem.create(name: "Negril", description: "This elegant Caribbean eatery set in a renovated 1907 firehouse offers a full bar & Sunday brunch.", address: "30 North Avenue NE, Atlanta, GA 30308", category_id: 2, img_url: "https://hungryshutterbug.files.wordpress.com/2018/08/img_4450.jpg?w=764" )
folk_art = CityGem.create(name: "Folk Art", description: "Brick-walled spot with vintage decor whipping up home-style fare & cocktails with a stylish twist.", address: "465 North Highland Avenue Northeast, Atlanta, GA 30307", category_id: 2, img_url: "https://cdn.vox-cdn.com/thumbor/tFb9_Yffsr8TNFEcWxZIVUM_nHY=/49x0:522x355/1200x800/filters:focal(49x0:522x355)/cdn.vox-cdn.com/uploads/chorus_image/image/38890528/eater0813_folkart.0.png" )
tenth_piedmont = CityGem.create(name: "10th & Piedmont", description: "Small plates mix global cuisine with Southern accents in a modern space with late-night DJs.", address: "991 Piedmont Ave NE, Atlanta, GA 30309", category_id: 2, img_url: "https://eventective-media.azureedge.net/1791794_md.jpg" )
nine_mile_station = CityGem.create(name: "9 Mile Station", description: "Rooftop beer garden with local brews, creative pub fare & city views from atop Ponce City Market", address: "675 Ponce De Leon Ave NE, Atlanta, GA 30308", category_id: 2, img_url: "https://static1.squarespace.com/static/5800c7eb29687f13a412f1ff/t/58d580216a4963a07f036c45/1490387067436/8Q9A9452.jpg?format=1500w" )
dwarf_house = CityGem.create(name: "Chick-fil-A Hapeville Dwarf House", description: "Welcome to the Hapeville Dwarf House, home of Chick-fil-A! On May 26, 1946, Truett Cathy and his brother Ben Cathy opened up a small restaurant in Hapeville, Georgia called the Dwarf Grill. What started out as a small dream turned into over 2,000 restaurants nationwide. 70 years and one name change later, the Hapeville Dwarf House is thriving today. Unlike your typical Chick-fil-A, the Hapeville Dwarf House has a full-service side and is open 24 hours, 6 days a week. But, don't worry, you can find everything you love on Chick-fil-A's menu here, plus some.", address: "461 N Central Ave, Hapeville, GA 30354", category_id: 2, img_url: "https://media-cdn.tripadvisor.com/media/photo-s/0e/72/52/6a/chick-fil-a-dwarf-house.jpg")
tdh = CityGem.create(name: "Tom, Dick and Hank", description: "Rustic-chic joint featuring BBQ with a modern twist, plus a rooftop bar serving craft cocktails.", address: "191 Ralph David Abernathy Blvd SW, Atlanta, GA 30312", category_id: 2, img_url: "http://www.tomdickandhank.com/wp-content/uploads/2015/07/IMG_9747.jpg" )
sweet_auburn = CityGem.create(name: "Sweet Auburn", description: "Nouveau-rustic outpost serving smoked meats & sides with eclectic touches, plus inventive cocktails.", address: "656 North Highland Avenue Northeast, Atlanta, GA 30306", category_id: 2, img_url: "http://atlanta-food-critic.com/wp-content/uploads/2016/04/sweet-auburn-barbecue-poncey-highlands-atlanta.jpg" )
old_lady_gang = CityGem.create(name: "Old Lady Gang", description: "Buzzy spot for soul food classics & all-Sunday-long brunch, courtesy of Atlanta reality-TV royalty.", address: "177 Peters St SW, Atlanta, GA 30313", category_id: 2, img_url: "https://i.pinimg.com/474x/4b/6c/34/4b6c3482a80f2a53204021508c6cb79d.jpg" )
busy_bee = CityGem.create(name: "Busy Bee", description: "Circa-1947 Downtown classic still serves traditional soul food at budget prices in cozy storefront.", address: "810 M.L.K. Jr Dr SW, Atlanta, GA 30314", category_id: 2, img_url: "http://www.soulofamerica.com/wp-content/uploads/2016/01/Atl-Busy_Bee_Cafe.jpg" )
gaja_korean_bar = CityGem.create(name: "Gaja Korean Bar", description: "Small, hip spot offering a focused menu of traditional Korean dishes given contemporary spins.", address: "491 Flat Shoals Ave SE A, Atlanta, GA 30316", category_id: 2, img_url: "https://i1.wp.com/www.remarqed.com/wp-content/uploads/2017/12/IMG_20171223_190033.jpg" )
sublime = CityGem.create(name: "Sublime Doughnuts", description: "Quaint shop doing donuts in a variety of adventurous flavors like maple-bacon-cheddar & red velvet.", address: "535 10th St NW, Atlanta, GA 30318", category_id: 2, img_url: "https://s3-media3.fl.yelpcdn.com/bphoto/Sc-DqCmX171HXlGeC5DQTQ/ls.jpg" )
vegan_dream = CityGem.create(name: "Vegan Dream Doughnuts", description: "All natural vegan doughnuts without eggs, milk and sugar.", address: "576 Lee St SW E, Atlanta, GA 30310", category_id: 2, img_url: "http://nebula.wsimg.com/4feeedd3f10558fb0876296e1b24de37?AccessKeyId=0361C0C5C20F6DB61390&disposition=0&alloworigin=1" )
eight_arm = CityGem.create(name: "8arm", description: "Casually hip daytime cafe serving New American fare, with more composed dishes for dinner.", address: "710 Ponce De Leon Ave NE, Atlanta, GA 30306", category_id: 2, img_url: "https://cdn.vox-cdn.com/thumbor/-XlpQPh7RzrAdyvS3ZZeCYKEMi8=/0x117:1500x961/1600x900/cdn.vox-cdn.com/uploads/chorus_image/image/54962267/JTP_3687.0.jpg" )
argosy = CityGem.create(name: "Argosy", description: "Stylish gastropub featuring New American fare & a vast craft beer list in wood & exposed-brick digs.", address: "470 Flat Shoals Ave SE, Atlanta, GA 30316", category_id: 2, img_url: "https://static.squarespace.com/static/511490efe4b0f297c486b7de/t/5148e81ce4b0a8477901738f/1363732508189/P1090003.JPG" )
rag_o_roma = CityGem.create(name: "Rag-O-Roma", description: "Cosignment clothing store featuring gently used clothing, accessories, jewelry & wigs.", address: "1111 Euclid Ave NE, Atlanta, GA 30307", category_id: 3, img_url: "http://3.bp.blogspot.com/_MjDFDx7oHE4/SwnfANxDn_I/AAAAAAAAADc/miCRj2iqTDk/s400/rag-o-rama.jpg" )
wish_atl = CityGem.create(name: "Wish ATL", description: "Edgy retailer stocking trendy, urban men's & women's fashions & a serious selection of sneakers.", address: "447 Moreland Ave NE, Atlanta, GA 30307", category_id: 3, img_url: "https://burnaway.org/wp-content/uploads/2018/01/WISH.jpg" )
abbadabba = CityGem.create(name: "Abbadabba", description: "Atlanta's Premier source for COOL SHOES - innovative and healthy footwear - sandals, shoes and boot", address: "421-B Moreland Avenue N.E. Atlanta, GA 30307", category_id: 3, img_url: "https://www.coolshoes.com/uploads/1/0/7/5/107516375/header-l5p-top-900w_orig.jpg" )
heet_atl = CityGem.create(name: "Heet ATL", description: "Compact, modern boutique for new & refurbished limited-edition sneakers, also buying on consignment.", address: "1149 Euclid Ave NE, Atlanta, GA 30307", category_id: 3, img_url: "https://i.ytimg.com/vi/XjTwEM9g5R4/maxresdefault.jpg" )
god_is_dope = CityGem.create(name: "God is Dope", description: "Playful boutique selling its own brand of streetwear & accessories with the 'God Is Dope' message.", address: "451 Edgewood Ave SE, Atlanta, GA 30312", category_id: 3, img_url: "https://cdn.cnn.com/cnnnext/dam/assets/180111181133-10-god-is-dope-clothing-super-tease.jpg" )
variety_plahouse = CityGem.create(name: "Variety Playhouse", description: "Converted movie theater now serves as an intimate concert hall featuring a variety of popular acts.", address: "1099 Euclid Ave NE, Atlanta, GA 30307", category_id: 4, img_url: "https://perkinswill.com/sites/default/files/styles/pw_full_image/public/project-imagery/varietyplayhouse_openingnight_tycho_alivecoverage88_0.jpg?itok=YJgnAs6O" )
  painted_duck = CityGem.create(name: "The Painted Duck ", description: "Refined nightlife space offering bowling & other social games alongside cocktails & modern bar food.", address: "976 Brady Ave NW, Atlanta, GA 30318", category_id: 6, img_url: "https://cdn.vox-cdn.com/thumbor/WsrCkgNnV83RMM11kGvU5F3geLg=/0x0:4000x2667/1200x0/filters:focal(0x0:4000x2667):no_upscale()/cdn.vox-cdn.com/uploads/chorus_asset/file/9933835/ThePaintedDuck_4.jpg" )
painted_pin = CityGem.create(name: "The Painted Pin", description: "Upscale bowling alley offering beer, modern snacks & bar food, plus bocce, Ping-Pong & Skee-Ball.", address: "737 Miami Cir NE, Atlanta, GA 30324", category_id: 6, img_url: "https://res.cloudinary.com/simpleview/image/upload/w_485,h_300,c_fill/crm/atlanta/J0062064_31b469d6-5056-b3a8-490693d97fb7ef22.jpg" )
starlight_six = CityGem.create(name: "Starlight Six Drive-In", description: "Double features, concessions to purchase (or BYO food) plus flea market on the weekends.", address: "2000 Moreland Ave SE, Atlanta, GA 30316", category_id: 6, img_url: "https://media-cdn.tripadvisor.com/media/photo-s/05/0c/cf/b0/starlight-six-drive-in.jpg" )
escobar = CityGem.create(name: "Escobar", description: "Cool locale with a swanky vibe for American comfort food, tapas & clever cocktails, plus hookah.", address: "327 Peters St SW, Atlanta, GA 30313", category_id: 5, img_url: "https://bizbash-production.imgix.net/content/editorial/storyimg/big/esco-pic.jpg?auto=format" )
two_five_five_lounge = CityGem.create(name: "255 Lounge", description: "Lounge & patio with VIP cabanas for cocktails & New American dishes like sliders & Asian rice bowls.", address: "255 Peters St SW, Atlanta, GA 30313", category_id: 5, img_url: "http://www.255tapaslounge.com/_assets/img/site_imgs/home_slider/255tapasloungelargeinterior.jpg" )
cafe_circa = CityGem.create(name: "Cafe Circa", description: "Chic lounge & restaurant serving Latin & Caribbean fare with a rooftop space for live music.", address: "464 Edgewood Ave SE, Atlanta, GA 30312", category_id: 5, img_url: "https://cdn.evbuc.com/eventlogos/196179102/a0717034a32c43589215f9faf15864c4.jpeg" )
joystick_gamebar = CityGem.create(name: "Joystick Gamebar", description: "Casual bar boasting arcade games & pinball & dishing up jumbo burgers & reimagined bar bites.", address: "427 Edgewood Ave SE, Atlanta, GA 30312", category_id: 5, img_url: "http://www.georgiastatehomes.com/files/Image/8587-ImageLarge-joystick-3" )
edgewood_speakeasy = CityGem.create(name: "Edgewood Speakeasy", description: "A creative cocktail bar with exposed brick walls & low lighting, hidden at the back of a pizzeria.", address: "327 Edgewood Ave SE, Atlanta, GA 30312", category_id: 5, img_url: "https://static.urbandaddy.com/uploads/assets/image/slideshows/standard/e3d9e6ec5ef94229bec4e851a5dbd19f.jpg" )
mothers = CityGem.create(name: "Mother’s", description: "This happening, multi-level establishment offers mixed drinks, bar bites, dancing & a patio.", address: "447 Edgewood Ave SE, Atlanta, GA 30312", category_id: 5, img_url: "https://static1.squarespace.com/static/56a4b4253b0be33df886c0c1/t/56aabe44d82d5eb7b7444896/1478839555045/MTbar1.jpg?format=2500w" )
church = CityGem.create(name: "Church", description: "Church-themed bar with picnic-style eats, church-organ karaoke & weekly Ping-Pong tournaments.", address: "466 Edgewood Ave SE, Atlanta, GA 30312", category_id: 5, img_url: "https://cdn-image.travelandleisure.com/sites/default/files/styles/marquee_large_2x/public/1448396218/sister-louisas-church-of-the-living-room-atlanta-at1115.jpg?itok=J0C3yUbF" )
cafe_instanbul = CityGem.create(name: "Cafe Instanbul", description: "Casual, lively spot with floor seating, Turkish-Mediterranean fare, hookah, drinks & belly dancers.", address: "1850 Lawrenceville Hwy, Decatur, GA 30033", category_id: 5, img_url: "https://media-cdn.tripadvisor.com/media/photo-s/04/5a/ed/84/cafe-istanbul.jpg" )
revery = CityGem.create(name: "Revery: VR Bar", description: "Revery is the nation's first full bar (Sorry, Kiddos it's 21+) to incorporate the virtual reality technology (SIMILAR TO A KARAOKE EXPERIENCE)", address: "728 Monroe Dr NE Suite C, Atlanta, GA 30308", category_id: 5, img_url: "https://www.wheretraveler.com/sites/default/files/styles/body_full_width/public/bar1_1.jpg?itok=oj3XvGuY" )
tongue_and_groove = CityGem.create(name: "Tongue and Groove", description: "This sleek nightclub with luxe decor is a lively spot for dancing & private party table service.", address: "565 Main St NE, Atlanta, GA 30324", category_id: 5, img_url: "https://www.playgroundatlanta.com/book/wp-content/sabai/File/files/e36024152dc362c27b747a935fe85dcc.png" )
boogalou = CityGem.create(name: "Boogalou", description: "Modern comfort food & cocktails offered in a glossy space with bar swings, banquettes & weekend DJs.", address: "239 Ponce De Leon Ave NE, Atlanta, GA 30308", category_id: 5, img_url: "http://www.boogalooswings.com/wp-content/uploads/2014/03/swing-pic-2.jpg" )
mjq_concourse = CityGem.create(name: "MJQ Concourse", description: "High-energy, late-night, 21+ gathering place featuring guest DJs, dance parties & live bands.", address: "736 Ponce De Leon Ave NE, Atlanta, GA 30306", category_id: 5, img_url: "https://pbs.twimg.com/media/CMFDx-3WUAAPDrf.jpg" )
the_basement = CityGem.create(name: "The Basement", description: "A host of themed basement parties. ", address: "1245 Glenwood Ave SE, Atlanta, GA 30316", category_id: 5, img_url: "https://www.basementatl.com/img/TheBasement_og.jpg" )
graveyard = CityGem.create(name: "Graveyard", description: "High-energy watering hole featuring pitchers & pub grub, plus live music & DJ nights.", address: "1245 Glenwood Ave SE, Atlanta, GA 30316", category_id: 5, img_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTs4AURMqw2-XX0c1-25VK0F4hgTW2pTTSnQulrG5Q9FWdRUUqh" )
el_bar = CityGem.create(name: "El Bar", description: "Basement dive bar with limited space but great music. ", address: "939 Ponce De Leon Ave NE, Atlanta, GA 30306", category_id: 5, img_url: "https://s3-media3.fl.yelpcdn.com/bphoto/1kd8QOc8dGbIAdXTAbTypQ/o.jpg" )
jp_alfonso = CityGem.create(name: "JP Alfonso Studios", description: "Gwinnett County's newest and best tattoo studio featuring the multi award winning, internationally recognized art of Jp Alfonso.", address: "5059 Jimmy Carter Blvd, Norcross, GA 30093", category_id: 4, img_url: "https://scontent-atl3-1.xx.fbcdn.net/v/t1.0-1/19959478_1823107061336552_5692566782482917153_n.jpg?_nc_cat=104&_nc_ht=scontent-atl3-1.xx&oh=0d56e7ce6b6d61bf23e125a39f021c2b&oe=5C6ABC4B" )
apocalypse_tattoo = CityGem.create(name: "Apocalypse Tattoo", description: "Providing the tattoo community in Atlanta and beyond with a world-class experience! Our commitment to you extends beyond the quality of your tattoo.", address: "3115 Piedmont Road Northeast a201-202, Atlanta, GA 30305", category_id: 4, img_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQeJu7iNgVz6o6cWOgK90xrCPZ3Cb9Aw9nYfcn36FQT5iy1NkzTpQ" )
ponce_city_market = CityGem.create(name: "Ponce City Market ", description: "The classic structure, which is the area’s largest adaptive reuse project, has been reinvented as a vibrant community hub housing the Central Food Hall, various shops, flats and offices, all while pointing back to the roots of its inception. The market infuses vigor and excitement into this historically-signiﬁcant structure, located in one of Atlanta’s most cherished neighborhoods.", address: "675 Ponce De Leon Ave NE, Atlanta, GA 30308", category_id: 4, img_url: "https://www.atlanta.net/uploadedImages/Content/Things_To_Do/Shopping/ponce-city-market-joleen-pete-photography-748x448.jpg" )
little_five = CityGem.create(name: "Little Five Points", description: "Little Five Points is one of Atlanta’s hippest neighborhoods. Shoppers head to Moreland Avenue’s indie stores for offbeat vintage clothing, vinyl and cool gifts, while young locals hang out at the dive bars, burger joints, and Ethiopian and vegan eateries that line the surrounding streets. The Variety Playhouse, a live music venue in a converted 1940s cinema, hosts an eclectic range of local and national acts.", address: "Candler Park", category_id: 4, img_url: "http://data.websitebox.com/data/users/0004/397/uploads/RWN_50thingslittle5points145abhjpg.jpg" )
krog_street_market = CityGem.create(name: "Krog Street Market", description: "Krog Street Market is a 9-acre mixed-use development in Atlanta, located along the BeltLine trail at Edgewood Avenue in Inman Park which opened in Summer 2014. The complex is centered on a 12,000-square-foot, west coast-style market and restaurants, and also includes up to 300 apartments.", address: "99 Krog St NE, Atlanta, GA 30307", category_id: 4, img_url: "https://www.ajc.com/rf/image_large/Pub/p8/AJC/2017/05/10/Videos/5429057610001.vpx.jpg" )
capellas = CityGem.create(name: "A Cappella Books", description: "Bookstore for new, used & rare titles in music, politics & other genres, plus frequent signings.", address: "208 Haralson Ave NE, Atlanta, GA 30307", category_id: 4, img_url: "https://www.acappellabooks.com/images/custom/Center_Pic.jpg")
little_free_library = CityGem.create(name: "Little Free Library ", description: "Little Free Library is a 501 nonprofit organization that aims to inspire a love of reading, build community, and spark creativity by fostering neighborhood book exchanges around the world.", address: "multiple locations", category_id: 4, img_url: "https://cdn.nybooks.com/wp-content/uploads/2014/05/darnton_1-052214.jpg" )
woodruff_museum = CityGem.create(name: "Woodruff Museum", description: "Woodruff Arts Center is a visual and performing arts center located in Atlanta, Georgia. The center houses three not-for-profit arts divisions on one campus.", address: "1280 Peachtree St NE, Atlanta, GA 30309", category_id: 4, img_url: "https://theturnaroundauthority.files.wordpress.com/2012/11/1354036271-woodruff-art-center-high-museum-h.jpg?w=600" )
jimmy_carter_museum = CityGem.create(name: "Jimmy Carter Museum", description: "The Jimmy Carter Library and Museum in Atlanta, Georgia houses U.S. President Jimmy Carter's papers and other material relating to the Carter administration and the Carter family's life.", address: "441 John Lewis Freedom Pkwy NE, Atlanta, GA 30307", category_id: 4, img_url: "https://res.cloudinary.com/simpleview/image/upload/w_485,h_300,c_fill/crm/atlanta/IMG_8889_2aaf4be7-5056-b3a8-4901ad3fe00e4b15.jpg" )
hammonds_house_museum = CityGem.create(name: "Hammonds House Museum", description: "The Hammonds House Museum is a museum for African American fine art, located in the 1872 Victorian house, former residence of Dr. Otis Thrash Hammonds, a prominent Atlanta physician and patron of the arts.", address: "503 Peeples St SW, Atlanta, GA 30310", category_id: 4, img_url: "https://static1.squarespace.com/static/58b708a9414fb5f538562978/t/599e4fbc46c3c4f77bbb9129/1503547346429/17499461_10208921092281384_1581025982343290516_n.jpg" )
waffle_house_museum = CityGem.create(name: "The Waffle House Museum", description: "The Waffle House ® Museum is the site of the very first Waffle House ® restaurant. It opened back in 1955 after two neighbors, Joe Rogers, Sr. and Tom Forkner, decided Avondale Estates needed a 24-hour restaurant.", address: "2719 E College Ave, Decatur, GA 30030", category_id: 4, img_url: "https://www.roadsideamerica.com/attract/images/ga/GADECwaffle_ks02.jpg" )
paris_on_ponce = CityGem.create(name: "Paris on Ponce", description: "Eclectic mix of 30-plus curators, collectors & designers offering mostly vintage furniture & decor.", address: "716 Ponce De Leon Pl NE, Atlanta, GA 30306", category_id: 4, img_url: "https://michellescottphoto.com/wp-content/uploads/2016/05/Kristen-Hillary-Paris-on-Ponce-Wedding-Photographer-115.jpg" )
botanical_gardens= CityGem.create(name: "Botanical Gardens", description: "The Atlanta Botanical Garden is a 30 acres botanical garden located adjacent to Piedmont Park in Midtown Atlanta, Georgia, United States. Incorporated in 1976, the garden's mission is to: develop and maintain plant collections for the purposes of display, education, conservation, research and enjoyment.", address: "1345 Piedmont Ave NE, Atlanta, GA 30309", category_id: 4, img_url: "https://www.wheretraveler.com/sites/default/files/styles/wt17_promoted_large/public/images/AtlBotanicalGdn_c-EricSonstroem-Flickr.jpg?itok=QWJdW4ia&timestamp=1450288900" )
trap_museum= CityGem.create(name: "Trap Museum", description: "A hybrid art gallery and interactive exhibit, displaying realisticscenes that are symbolic of the sound and lifestyle, that originated in the ATL.", address: "630 Travis St NW, Atlanta, GA 30318", category_id: 4, img_url: "https://s3.amazonaws.com/s3.wveefm.radio.com/styles/delta__775x515/s3/Future-and-Migos-Walls.jpg?itok=UJ8FeZL8" )
high_museum= CityGem.create(name: "High Museum", description: "The High Museum of Art, located in Atlanta, is a leading art museum in the Southeastern United States. Located on Peachtree Street in Midtown, the city's arts district, the High is a division of the Woodruff Arts Center. I", address: "1280 Peachtree St NE, Atlanta, GA 30309", category_id: 4, img_url: "https://res.cloudinary.com/atlanta/image/upload/w_400/ACVBLeisure/uploadedImages/Photogallery/Atlanta-High-Museum-of-Art-Skylight-Gallery-2.jpg" )
the_loft= CityGem.create(name: "The Loft", description: "Apart of Center Stage three separate venues located in Atlanta, Georgia.", address: "1374 West Peachtree Street Northwest, Atlanta, GA 30309", category_id: 4, img_url: "http://www.centerstage-atlanta.com/wp-content/gallery/the-loft/loft_vipbar_web.jpg" )
eddies_attick = CityGem.create(name: "Eddie’s Attic", description: "Eddie's Attic is a music club in Decatur, Georgia. Founded in 1992 by Eddie Owen, it is a venue for both local musical talent and musicians of some acclaim who often got their start in the Atlanta area.", address: "1374 West Peachtree Street Northwest, Atlanta, GA 30309", category_id: 4, img_url: "https://i.pinimg.com/originals/fe/2f/4b/fe2f4be313585acd8250bddbb564e0cc.jpg" )
center_stage = CityGem.create(name: "Center Stage", description: "Center Stage is a mid-sized concert complex comprising three separate venues located in Atlanta, Georgia.", address: "1374 West Peachtree Street Northwest, Atlanta, GA 30309", category_id: 4, img_url: "http://www.centerstage-atlanta.com/wp-content/gallery/center-stage/cs_fullhousetostage2_web.jpg" )

comments =[ {body: "This is a great little coffee shop. Cappuccino was smooth with just enough milk to not over power the coffee. In the three times I stopped in, two of the cappuccino tasted the same and the third was a little to hot with a little to much milk... but overall I would go here again.", user_id: 2, city_gem_id: 13 }, {body: "Charleston Park is a hidden little mountain biking fast track trail located on the edge of lake Lanier. Only well known by older locals makeing it a great place to ride when your looking for less of a crowd, downhill speed, and a wonderful day of dusty fast track.", user_id: 2, city_gem_id: 4}]

comments.each do |comment|
  Comment.create(comment)
end
